name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
# req file not needed for unit tests
#          python -m pip install -r pip-reqs.txt
      - name: install package locally
        run: |
          python3 -m pip install -e .
      - name: run unit tests
        run: |
          python -m unittest -v unit_test/test_*
